version: "3.8"
services:
  bskybot:
    depends_on:
      - jetstream
    build: .
    restart: unless-stopped
    volumes:
      - ./sessionData:/sessionData
    env_file:
      - .env
    networks:
      - bun


  jetstream:
    image: "ghcr.io/bluesky-social/jetstream:sha-ea96859b93d1790ff20bb168e5fc442d462cea1e"
    container_name: jetstream
    restart: unless-stopped
    environment:
      - CURSOR_FILE=/data/cursor.json
    ports:
      - "6008:6008"
    volumes:
      - ./data:/data
    networks:
      - bun

networks:
  bun:
    driver: bridge
